name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Hello, World!
        run: make say-hello
